name: LT-VT
on: [pull_request]   
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: LT-V
        uses: Shivanshu-lambdatest/Github-VT-Plugin@Review-Check-v19
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
