name: LT-VT
on: 
  check_run:
    type: created
    
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: LT-V
        uses: Shivanshu-lambdatest/Github-VT-Plugin@Review-Check-v18
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APP_ID: ${{ secrets.APP_ID }}
          INSTALL_ID: ${{ secrets.INSTALL_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

